import { Employee } from '@/lib/types/employees';

export const mockEmployees: Employee[] = [
  {
    id: 'EMP-001',
    employeeId: 'TSL001',
    name: 'Rajesh Kumar',
    email: 'rajesh@tsl.com',
    phone: '+91 9876543210',
    department: 'environmental',
    role: 'project-manager',
    designation: 'Senior Project Manager',
    joiningDate: new Date('2020-01-15'),
    experience: 10,
    expertise: ['Project Management', 'EIA', 'Team Leadership'],
    currentProjects: ['PRJ-001', 'PRJ-003'],
    assignedTasks: ['TSK-001', 'TSK-002'],
    totalTasks: 15,
    completedTasks: 12,
    pendingTasks: 3,
    performanceScore: 92,
    isActive: true,
    createdAt: new Date('2020-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'EMP-002',
    employeeId: 'TSL002',
    name: 'Priya Sharma',
    email: 'priya@tsl.com',
    phone: '+91 9876543211',
    department: 'environmental',
    role: 'eia-expert',
    designation: 'EIA Specialist',
    joiningDate: new Date('2021-03-10'),
    experience: 8,
    expertise: ['Environmental Assessment', 'Report Writing', 'Compliance'],
    currentProjects: ['PRJ-001'],
    assignedTasks: ['TSK-002'],
    totalTasks: 8,
    completedTasks: 6,
    pendingTasks: 2,
    performanceScore: 88,
    isActive: true,
    createdAt: new Date('2021-03-10'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'EMP-003',
    employeeId: 'TSL003',
    name: 'Amit Patel',
    email: 'amit@tsl.com',
    phone: '+91 9876543212',
    department: 'engineering',
    role: 'field-engineer',
    designation: 'Field Engineer',
    joiningDate: new Date('2022-06-20'),
    experience: 5,
    expertise: ['Site Survey', 'Technical Analysis', 'Field Work'],
    currentProjects: ['PRJ-001', 'PRJ-002'],
    assignedTasks: ['TSK-001', 'TSK-003'],
    totalTasks: 10,
    completedTasks: 9,
    pendingTasks: 1,
    performanceScore: 85,
    isActive: true,
    createdAt: new Date('2022-06-20'),
    updatedAt: new Date('2024-01-31'),
  },
  {
    id: 'EMP-004',
    employeeId: 'TSL004',
    name: 'Sneha Verma',
    email: 'sneha@tsl.com',
    phone: '+91 9876543213',
    department: 'legal',
    role: 'consultant',
    designation: 'Legal Consultant',
    joiningDate: new Date('2019-08-05'),
    experience: 12,
    expertise: ['Legal Compliance', 'Documentation', 'Contracts'],
    currentProjects: ['PRJ-003'],
    assignedTasks: ['TSK-004'],
    totalTasks: 6,
    completedTasks: 5,
    pendingTasks: 1,
    performanceScore: 90,
    isActive: true,
    createdAt: new Date('2019-08-05'),
    updatedAt: new Date('2024-02-10'),
  },
];