import { Project } from '@/lib/types/projects';

export const mockProjects: Project[] = [
  {
    id: 'PRJ-001',
    name: 'Solar Power Plant - Rajasthan',
    description: '500MW solar power plant with environmental impact assessment',
    type: 'EIA',
    status: 'in-progress',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-06-30'),
    location: {
      state: 'Rajasthan',
      district: 'Jaisalmer',
      city: 'Jaisalmer',
      coordinates: { lat: 26.9157, lng: 70.9083 },
    },
    teamLeadId: 'EMP-001',
    teamMemberIds: ['EMP-002', 'EMP-003', 'EMP-004'],
    department: 'environmental',
    progress: 65,
    budget: {
      allocated: 2500000000,
      utilized: 1625000000,
      currency: 'INR',
    },
    eiaRequired: true,
    eiaNumber: 'EIA/RJ/2024/001',
    clearanceDate: new Date('2024-03-15'),
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-02-15'),
    createdBy: 'EMP-001',
    documents: ['eia-report.pdf'],
    tags: ['renewable', 'solar'],
  },
  {
    id: 'PRJ-002',
    name: 'Wind Farm - Gujarat',
    description: '250MW wind energy project',
    type: 'EC',
    status: 'completed',
    startDate: new Date('2023-11-01'),
    endDate: new Date('2024-02-28'),
    location: {
      state: 'Gujarat',
      district: 'Kutch',
      city: 'Bhuj',
    },
    teamLeadId: 'EMP-005',
    teamMemberIds: ['EMP-006', 'EMP-007'],
    department: 'engineering',
    progress: 100,
    budget: {
      allocated: 1500000000,
      utilized: 1450000000,
      currency: 'INR',
    },
    eiaRequired: false,
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2024-02-28'),
    createdBy: 'EMP-005',
    documents: [],
    tags: ['wind', 'renewable'],
  },
  {
    id: 'PRJ-003',
    name: 'Hydroelectric Project - Himachal',
    description: '100MW hydro power plant',
    type: 'Hybrid',
    status: 'delayed',
    startDate: new Date('2023-12-10'),
    endDate: new Date('2024-05-15'),
    location: {
      state: 'Himachal Pradesh',
      district: 'Kinnaur',
      city: 'Reckong Peo',
    },
    teamLeadId: 'EMP-008',
    teamMemberIds: ['EMP-009', 'EMP-010'],
    department: 'environmental',
    progress: 45,
    budget: {
      allocated: 3200000000,
      utilized: 1440000000,
      currency: 'INR',
    },
    eiaRequired: true,
    eiaNumber: 'EIA/HP/2023/045',
    createdAt: new Date('2023-11-20'),
    updatedAt: new Date('2024-02-10'),
    createdBy: 'EMP-008',
    documents: ['feasibility-study.pdf'],
    tags: ['hydro', 'delayed'],
  },
  {
    id: 'PRJ-004',
    name: 'Thermal Plant Expansion - Maharashtra',
    description: 'Capacity expansion of existing thermal plant',
    type: 'EIA',
    status: 'planned',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-12-31'),
    location: {
      state: 'Maharashtra',
      district: 'Raigad',
      city: 'Navi Mumbai',
    },
    teamLeadId: 'EMP-011',
    teamMemberIds: ['EMP-012', 'EMP-013'],
    department: 'engineering',
    progress: 0,
    budget: {
      allocated: 5000000000,
      utilized: 0,
      currency: 'INR',
    },
    eiaRequired: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    createdBy: 'EMP-011',
    documents: [],
    tags: ['thermal', 'expansion'],
  },
];