import { Task } from '@/lib/types/tasks';

export const mockTasks: Task[] = [
  {
    id: 'TSK-001',
    projectId: 'PRJ-001',
    title: 'Site Survey and Assessment',
    description: 'Conduct detailed site survey',
    assigneeId: 'EMP-003',
    assigneeName: 'Amit Patel',
    status: 'completed',
    priority: 'high',
    progress: 100,
    startDate: new Date('2024-01-20'),
    dueDate: new Date('2024-01-31'),
    estimatedHours: 80,
    actualHours: 75,
    dependencies: [],
    updates: [
      {
        id: 'UPDATE-001',
        taskId: 'TSK-001',
        userId: 'EMP-003',
        userName: 'Amit Patel',
        progress: 50,
        notes: 'Soil testing completed',
        attachments: [],
        date: new Date('2024-01-25'),
      },
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-31'),
    createdBy: 'EMP-001',
    attachments: ['survey-report.pdf'],
    tags: ['field-work'],
  },
  {
    id: 'TSK-002',
    projectId: 'PRJ-001',
    title: 'Environmental Impact Assessment',
    description: 'Prepare EIA report',
    assigneeId: 'EMP-002',
    assigneeName: 'Priya Sharma',
    status: 'in-progress',
    priority: 'critical',
    progress: 80,
    startDate: new Date('2024-02-01'),
    dueDate: new Date('2024-03-15'),
    estimatedHours: 120,
    actualHours: 96,
    dependencies: ['TSK-001'],
    updates: [
      {
        id: 'UPDATE-002',
        taskId: 'TSK-002',
        userId: 'EMP-002',
        userName: 'Priya Sharma',
        progress: 80,
        notes: 'Draft report under review',
        attachments: [],
        date: new Date('2024-02-20'),
      },
    ],
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-20'),
    createdBy: 'EMP-001',
    attachments: ['eia-draft.pdf'],
    tags: ['report', 'eia'],
  },
  {
    id: 'TSK-003',
    projectId: 'PRJ-002',
    title: 'Wind Turbine Installation',
    description: 'Install 50 wind turbines',
    assigneeId: 'EMP-006',
    assigneeName: 'Rahul Verma',
    status: 'completed',
    priority: 'high',
    progress: 100,
    startDate: new Date('2023-12-01'),
    dueDate: new Date('2024-01-31'),
    estimatedHours: 200,
    actualHours: 190,
    dependencies: [],
    updates: [],
    createdAt: new Date('2023-11-20'),
    updatedAt: new Date('2024-01-31'),
    createdBy: 'EMP-005',
    attachments: ['installation-report.pdf'],
    tags: ['installation'],
  },
  {
    id: 'TSK-004',
    projectId: 'PRJ-003',
    title: 'Land Acquisition',
    description: 'Acquire land for project',
    assigneeId: 'EMP-009',
    assigneeName: 'Sanjay Kumar',
    status: 'blocked',
    priority: 'critical',
    progress: 60,
    startDate: new Date('2023-12-15'),
    dueDate: new Date('2024-02-15'),
    estimatedHours: 100,
    actualHours: 60,
    dependencies: [],
    blockerReason: 'Legal issues with land ownership',
    updates: [
      {
        id: 'UPDATE-003',
        taskId: 'TSK-004',
        userId: 'EMP-009',
        userName: 'Sanjay Kumar',
        progress: 60,
        notes: 'Facing legal challenges',
        attachments: [],
        date: new Date('2024-02-10'),
        blocker: 'Land dispute case in court',
      },
    ],
    createdAt: new Date('2023-12-10'),
    updatedAt: new Date('2024-02-10'),
    createdBy: 'EMP-008',
    attachments: ['legal-doc.pdf'],
    tags: ['legal', 'blocked'],
  },
];
